#!/usr/bin/env python3
"""
NIO Depth Raw Data (.raw) Parser & Point Cloud Generator

Data structure of .raw file:
  Header (44 bytes):
    [0:16]  Magic string: "NIO_DEPTH_RAW" (new) or "ORBBEC_DEPTH_RAW" (legacy)
    [16:20] Width       (uint32_t)
    [20:24] Height      (uint32_t)
    [24:28] BPP         (uint32_t) - bytes per pixel (2 for Y16)
    [28:32] Scale       (float32)  - depth unit scale (Orbbec: m/unit e.g. 0.001; RS-AC1: mm/unit e.g. 5.0)
    [32:36] FrameSize   (uint32_t) - bytes per frame (w*h*bpp)
    [36:44] StartTS     (uint64_t) - session start timestamp (ms)
  Frame data (repeating):
    [frameSize bytes each] - raw Y16 depth pixels (uint16_t per pixel)

If no header is found, the file is treated as raw Y16 frames
with dimensions specified via --width and --height.

Camera intrinsics are auto-loaded from _depth_intrinsic_*.json
(generated by nio_multi_capture). Override with --fx/--fy/--cx/--cy.

Usage:
  python3 parse_depth_raw_pcd.py <file.raw> [options]

Output options:
  --pointcloud    Generate 3D point cloud (PCD format, default)
  --png           Also save depth colorized PNG images
  --view          Open interactive 3D viewer (requires open3d)

Point cloud options:
  --fx F          Focal length X (default: auto from JSON or estimate)
  --fy F          Focal length Y (default: auto from JSON or estimate)
  --cx C          Principal point X (default: auto from JSON or width/2)
  --cy C          Principal point Y (default: auto from JSON or height/2)
  --max-depth-m M Max depth in meters for point cloud filtering (default: 10.0)

Other options:
  --width W       Image width (default: 640, auto-detect from header)
  --height H      Image height (default: 480, auto-detect from header)
  --scale S       Depth scale (default: 0.001)
  --frame N       Frame index (default: 0)
  --all           Process all frames
  --output DIR    Output directory (default: depth_pcd)
  --ascii         Print ASCII depth map to terminal
  --stats         Print depth statistics
  --colormap CM   Matplotlib colormap name (default: jet)
  --min-depth D   Minimum depth for colormap (mm)
  --max-depth D   Maximum depth for colormap (mm)
  --no-header     Force no-header mode (raw Y16 from start)

Examples:
  # Default: auto-load intrinsics from JSON, output PCD only:
  python3 parse_depth_raw_pcd.py capture.raw --pointcloud

  # PCD + PNG images:
  python3 parse_depth_raw_pcd.py capture.raw --pointcloud --png

  # With explicit intrinsics:
  python3 parse_depth_raw_pcd.py capture.raw --pointcloud --fx 481.2 --fy 480.0

  # Interactive 3D viewer:
  python3 parse_depth_raw_pcd.py capture.raw --pointcloud --view

  # All frames:
  python3 parse_depth_raw_pcd.py capture.raw --pointcloud --all
"""

import sys
import os
import struct
import argparse
import json
import numpy as np

def scale_to_mm_per_unit(scale):
    if scale < 1.0:
        return scale * 1000.0
    else:
        return scale


def parse_header(data):
    header = {}
    magic = data[0:16]
    if isinstance(magic, bytes):
        magic_str = magic.split(b'\x00')[0].decode('ascii', errors='replace')
    else:
        magic_str = str(magic)

    if magic_str.startswith('NIO_DEPTH_RAW') or magic_str.startswith('ORBBEC_DEPTH_RAW'):
        header['has_header'] = True
        header['magic'] = magic_str
        header['width'] = struct.unpack_from('<I', data, 16)[0]
        header['height'] = struct.unpack_from('<I', data, 20)[0]
        header['bpp'] = struct.unpack_from('<I', data, 24)[0]
        header['scale'] = struct.unpack_from('<f', data, 28)[0]
        header['frame_size'] = struct.unpack_from('<I', data, 32)[0]
        header['start_ts'] = struct.unpack_from('<Q', data, 36)[0]
        return header
    else:
        header['has_header'] = False
        return header


def parse_raw_file(filepath, width=640, height=480, scale=0.001, force_no_header=False):
    with open(filepath, 'rb') as f:
        data = f.read()

    file_size = len(data)
    header = {}

    if not force_no_header:
        header = parse_header(data)

    if header.get('has_header'):
        w = header['width']
        h = header['height']
        bpp = header['bpp']
        sc = header['scale']
        frame_size = header['frame_size']
        header_size = 44
        print(f"=== NIO Depth RAW File Header ===")
        print(f"  Magic:     {header['magic']}")
        print(f"  Width:     {w}")
        print(f"  Height:    {h}")
        print(f"  BPP:       {bpp}")
        print(f"  Scale:     {sc} ({'m/unit' if sc < 1.0 else 'mm/unit'})")
        print(f"  FrameSize: {frame_size} bytes")
        print(f"  StartTS:   {header['start_ts']} ms")
        print(f"  File size: {file_size} bytes")
    else:
        w = width
        h = height
        bpp = 2
        sc = scale
        frame_size = w * h * bpp
        header_size = 0
        print(f"=== No header detected, using defaults ===")
        print(f"  Width:     {w}")
        print(f"  Height:    {h}")
        print(f"  BPP:       {bpp}")
        print(f"  Scale:     {sc}")
        print(f"  FrameSize: {frame_size} bytes")
        print(f"  File size: {file_size} bytes")

    remaining = file_size - header_size
    if frame_size <= 0:
        print("ERROR: Invalid frame size")
        return None, None, None, None

    num_frames = remaining // frame_size
    print(f"  Num frames: {num_frames}")
    print(f"  Remaining bytes after last frame: {remaining % frame_size}")
    print()

    frames = []
    for i in range(num_frames):
        offset = header_size + i * frame_size
        frame_data = data[offset:offset + frame_size]
        depth_arr = np.frombuffer(frame_data, dtype=np.uint16).reshape((h, w))
        frames.append(depth_arr)

    return frames, w, h, sc


def load_intrinsic_json(raw_path):
    raw_base = os.path.splitext(raw_path)[0]
    candidates = [
        raw_base + "_intrinsic.json",
        raw_base.replace("_depth_raw_", "_depth_intrinsic_") + ".json",
    ]
    raw_dir = os.path.dirname(raw_path)
    raw_name = os.path.basename(raw_path)
    raw_name_base = os.path.splitext(raw_name)[0]
    ts_match = raw_name_base.rsplit('_', 1)[-1] if '_' in raw_name_base else ''
    if ts_match and len(ts_match) >= 13:
        candidates.append(
            os.path.join(raw_dir, raw_name_base.replace("_depth_raw_", "_depth_intrinsic_") + ".json"))
    if raw_dir:
        for fn in sorted(os.listdir(raw_dir)):
            if '_depth_intrinsic_' in fn and fn.endswith('.json'):
                candidates.append(os.path.join(raw_dir, fn))

    for path in candidates:
        if os.path.exists(path):
            try:
                with open(path, 'r') as f:
                    data = json.load(f)
                print(f"  Loaded intrinsic: {path}")
                return data
            except Exception as e:
                print(f"  WARNING: Failed to load {path}: {e}")
    return None


def print_ascii_depth(depth, w_out=80, h_out=24, scale=0.001):
    h, w = depth.shape
    mm_per_unit = scale_to_mm_per_unit(scale)
    depth_mm = depth.astype(np.float32) * mm_per_unit
    depth_mm[depth == 0] = -1

    chars = " .:-=+*#%@"
    max_depth = 5000.0
    min_depth = 200.0

    step_w = max(1, w // w_out)
    step_h = max(1, h // h_out)

    for y in range(0, h, step_h):
        line = ""
        for x in range(0, w, step_w):
            d = depth_mm[y, x]
            if d < 0:
                line += " "
            else:
                norm = (d - min_depth) / (max_depth - min_depth)
                norm = max(0.0, min(1.0, norm))
                ci = int(norm * (len(chars) - 1))
                line += chars[ci]
        print(line)


def print_stats(depth, frame_idx, scale=0.001):
    mm_per_unit = scale_to_mm_per_unit(scale)
    depth_mm = depth.astype(np.float64) * mm_per_unit
    valid = depth_mm[depth > 0]
    print(f"  Frame {frame_idx}:")
    print(f"    Total pixels:  {depth.size}")
    print(f"    Valid pixels:  {len(valid)} ({100.0*len(valid)/depth.size:.1f}%)")
    print(f"    Zero pixels:   {np.sum(depth == 0)} ({100.0*np.sum(depth==0)/depth.size:.1f}%)")
    if len(valid) > 0:
        print(f"    Min depth:     {valid.min():.1f} mm ({valid.min()/1000.0:.3f} m)")
        print(f"    Max depth:     {valid.max():.1f} mm ({valid.max()/1000.0:.3f} m)")
        print(f"    Mean depth:    {valid.mean():.1f} mm ({valid.mean()/1000.0:.3f} m)")
        print(f"    Median depth:  {np.median(valid):.1f} mm")
        print(f"    Std depth:     {valid.std():.1f} mm")
        percentiles = [10, 25, 50, 75, 90, 95, 99]
        vals = np.percentile(valid, percentiles)
        pstr = ", ".join(f"{p}%-ile={v:.0f}mm" for p, v in zip(percentiles, vals))
        print(f"    Percentiles:   {pstr}")
    print()


def save_colorized(depth, filepath, scale=0.001, colormap='jet',
                   min_depth=None, max_depth=None):
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
    except ImportError:
        print("ERROR: matplotlib required for image output. Install: pip3 install matplotlib")
        return

    mm_per_unit = scale_to_mm_per_unit(scale)
    depth_mm = depth.astype(np.float32) * mm_per_unit
    depth_vis = depth_mm.copy()
    depth_vis[depth == 0] = np.nan

    if min_depth is None:
        valid = depth_mm[depth > 0]
        min_depth = np.percentile(valid, 2) if len(valid) > 0 else 0
    if max_depth is None:
        valid = depth_mm[depth > 0]
        max_depth = np.percentile(valid, 98) if len(valid) > 0 else 5000

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    ax = axes[0]
    im = ax.imshow(depth_vis, cmap=colormap, vmin=min_depth, vmax=max_depth)
    ax.set_title('Depth Color Map')
    ax.set_xlabel('X (pixels)')
    ax.set_ylabel('Y (pixels)')
    plt.colorbar(im, ax=ax, label='Depth (mm)')

    ax = axes[1]
    valid_mask = depth > 0
    valid_depths = depth_mm[valid_mask]
    if len(valid_depths) > 0:
        ax.hist(valid_depths, bins=100, color='steelblue', edgecolor='none', alpha=0.8)
        ax.axvline(np.mean(valid_depths), color='red', linestyle='--', label=f'Mean={np.mean(valid_depths):.0f}mm')
        ax.axvline(np.median(valid_depths), color='orange', linestyle='--', label=f'Median={np.median(valid_depths):.0f}mm')
        ax.legend(fontsize=8)
    ax.set_title('Depth Histogram')
    ax.set_xlabel('Depth (mm)')
    ax.set_ylabel('Pixel Count')

    ax = axes[2]
    center_y = depth.shape[0] // 2
    cross_section = depth_mm[center_y, :]
    ax.plot(range(depth.shape[1]), cross_section, 'b-', linewidth=0.5)
    ax.set_title(f'Cross-section at y={center_y}')
    ax.set_xlabel('X (pixels)')
    ax.set_ylabel('Depth (mm)')
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(filepath, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"  Saved: {filepath}")


def save_histogram(depth, filepath, scale=0.001):
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
    except ImportError:
        print("ERROR: matplotlib required")
        return

    mm_per_unit = scale_to_mm_per_unit(scale)
    depth_mm = depth.astype(np.float32) * mm_per_unit
    valid = depth_mm[depth > 0]

    fig, ax = plt.subplots(figsize=(10, 6))
    if len(valid) > 0:
        ax.hist(valid, bins=200, color='steelblue', edgecolor='none', alpha=0.8)
        ax.axvline(np.mean(valid), color='red', linestyle='--',
                   label=f'Mean={np.mean(valid):.0f}mm')
        ax.axvline(np.median(valid), color='orange', linestyle='--',
                   label=f'Median={np.median(valid):.0f}mm')
        ax.legend()
    ax.set_title('Depth Distribution')
    ax.set_xlabel('Depth (mm)')
    ax.set_ylabel('Pixel Count')
    ax.grid(True, alpha=0.3)
    plt.savefig(filepath, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"  Saved: {filepath}")


def depth_to_pointcloud(depth, scale, fx, fy, cx, cy, max_depth_m=10.0):
    h, w = depth.shape
    if scale < 1.0:
        z = depth.astype(np.float64) * scale
    else:
        z = depth.astype(np.float64) * scale / 1000.0
    valid = (depth > 0) & (z <= max_depth_m)
    u = np.tile(np.arange(w, dtype=np.float64), (h, 1))
    v = np.tile(np.arange(h, dtype=np.float64).reshape(-1, 1), (1, w))
    x = (u - cx) * z / fx
    y = (v - cy) * z / fy
    points = np.stack([x[valid], y[valid], z[valid]], axis=-1)
    return points


# ====================== 核心修改：保存为 PCD 格式 ======================
def save_pcd(points, colors, filepath):
    """保存带颜色的点云为 PCD 二进制格式（PCL兼容）"""
    num_points = len(points)
    if num_points == 0:
        print(f"  无有效点，跳过保存: {filepath}")
        return

    # PCD 文件头
    header = f"""# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F U
COUNT 1 1 1 1
WIDTH {num_points}
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS {num_points}
DATA binary
"""

    # 颜色打包：RGB -> 一个uint32
    r = colors[:, 0].astype(np.uint32)
    g = colors[:, 1].astype(np.uint32)
    b = colors[:, 2].astype(np.uint32)
    rgb = (r << 16) | (g << 8) | b

    # 拼接数据：x y z (float32) + rgb (uint32)
    data = np.zeros((num_points, 4), dtype=np.float32)
    data[:, 0:3] = points.astype(np.float32)
    data[:, 3] = rgb.view(np.float32)

    # 写入文件
    with open(filepath, 'wb') as f:
        f.write(header.encode('utf-8'))
        f.write(data.tobytes())

    print(f"  Saved: {filepath} ({num_points} points)")
# ====================================================================


def depth_to_colored_pointcloud(depth, scale, fx, fy, cx, cy, max_depth_m=10.0,
                                 min_depth_m=0.3, colormap='jet'):
    points = depth_to_pointcloud(depth, scale, fx, fy, cx, cy, max_depth_m)
    if len(points) == 0:
        return points, np.zeros((0, 3), dtype=np.uint8)
    z_valid = points[:, 2]
    norm = (z_valid - min_depth_m) / (max_depth_m - min_depth_m)
    norm = np.clip(norm, 0.0, 1.0)
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
        cm = plt.get_cmap(colormap)
        colors = (cm(norm)[:, :3] * 255).astype(np.uint8)
    except ImportError:
        r = (norm * 255).astype(np.uint8)
        g = ((1.0 - np.abs(norm - 0.5) * 2) * 255).astype(np.uint8)
        b = ((1.0 - norm) * 255).astype(np.uint8)
        colors = np.stack([r, g, b], axis=-1)
    return points, colors


def view_pointcloud_open3d(points, colors=None):
    try:
        import open3d as o3d
    except ImportError:
        print("ERROR: open3d required for interactive viewer. Install: pip3 install open3d")
        return
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(points)
    if colors is not None:
        pcd.colors = o3d.utility.Vector3dVector(colors.astype(np.float64) / 255.0)
    print("Controls: mouse=rotate/translate, scroll=zoom, q/ESC=quit")
    o3d.visualization.draw_geometries([pcd], window_name="Depth Point Cloud",
                                      width=1280, height=720)


def main():
    parser = argparse.ArgumentParser(description='NIO Depth RAW Parser & Point Cloud Generator')
    parser.add_argument('file', help='Path to .raw file')
    parser.add_argument('--width', type=int, default=640, help='Image width')
    parser.add_argument('--height', type=int, default=480, help='Image height')
    parser.add_argument('--scale', type=float, default=0.001, help='Depth scale')
    parser.add_argument('--frame', type=int, default=0, help='Frame index')
    parser.add_argument('--all', action='store_true', help='Process all frames')
    parser.add_argument('--output', default='depth_pcd', help='Output directory')
    parser.add_argument('--ascii', action='store_true', help='Print ASCII depth map')
    parser.add_argument('--stats', action='store_true', help='Print depth statistics')
    parser.add_argument('--colormap', default='jet', help='Matplotlib colormap')
    parser.add_argument('--min-depth', type=float, default=None, help='Min depth (mm)')
    parser.add_argument('--max-depth', type=float, default=None, help='Max depth (mm)')
    parser.add_argument('--no-header', action='store_true', help='Force no-header mode')
    parser.add_argument('--pointcloud', action='store_true', help='Generate 3D point cloud (PCD)')
    parser.add_argument('--png', action='store_true', help='Also save depth PNG images')
    parser.add_argument('--fx', type=float, default=None, help='Focal length X')
    parser.add_argument('--fy', type=float, default=None, help='Focal length Y')
    parser.add_argument('--cx', type=float, default=None, help='Principal point X')
    parser.add_argument('--cy', type=float, default=None, help='Principal point Y')
    parser.add_argument('--view', action='store_true', help='Open interactive 3D viewer (open3d)')
    parser.add_argument('--max-depth-m', type=float, default=10.0, help='Max depth in meters for point cloud')
    args = parser.parse_args()

    if not os.path.exists(args.file):
        print(f"ERROR: File not found: {args.file}")
        sys.exit(1)

    result = parse_raw_file(args.file, args.width, args.height, args.scale, args.no_header)
    frames, w, h, scale = result

    if frames is None or len(frames) == 0:
        print("No frames found!")
        sys.exit(1)

    print(f"Loaded {len(frames)} frame(s) of {w}x{h}, scale={scale}\n")

    if args.ascii:
        idx = min(args.frame, len(frames) - 1)
        print(f"=== ASCII Depth Map (frame {idx}) ===")
        print_ascii_depth(frames[idx], scale=scale)
        print()

    if args.stats:
        print("=== Depth Statistics ===")
        if args.all:
            for i, frame in enumerate(frames):
                print_stats(frame, i, scale)
        else:
            idx = min(args.frame, len(frames) - 1)
            print_stats(frames[idx], idx, scale)

    if args.ascii or args.stats:
        if not args.png and not args.pointcloud and not args.view:
            return

    os.makedirs(args.output, exist_ok=True)

    if args.png:
        try:
            import matplotlib
            matplotlib.use('Agg')
            import matplotlib.pyplot as plt
        except ImportError:
            print("WARNING: matplotlib not installed, skipping PNG output")
            print("Install with: pip3 install matplotlib")
            args.png = False

    if args.png:
        if args.all:
            print(f"=== Generating PNG for {len(frames)} frames ===")
            for i, frame in enumerate(frames):
                outpath = os.path.join(args.output, f"frame_{i:06d}.png")
                save_colorized(frame, outpath, scale, args.colormap,
                              args.min_depth, args.max_depth)
        else:
            idx = min(args.frame, len(frames) - 1)
            outpath = os.path.join(args.output, f"frame_{idx:06d}.png")
            print(f"=== Generating PNG for frame {idx} ===")
            save_colorized(frames[idx], outpath, scale, args.colormap,
                          args.min_depth, args.max_depth)

    if args.pointcloud or args.view:
        intrinsic_data = load_intrinsic_json(args.file)
        if intrinsic_data:
            depth_intr = intrinsic_data.get('depth', {})
        else:
            depth_intr = {}

        fx = args.fx if args.fx is not None else depth_intr.get('fx', w * 0.75)
        fy = args.fy if args.fy is not None else depth_intr.get('fy', h * 0.75)
        cx = args.cx if args.cx is not None else depth_intr.get('cx', w / 2.0)
        cy = args.cy if args.cy is not None else depth_intr.get('cy', h / 2.0)
        min_depth_m = (args.min_depth / 1000.0) if args.min_depth else 0.3
        max_depth_m = args.max_depth_m

        src = "JSON" if intrinsic_data and 'fx' in depth_intr else ("CLI" if args.fx is not None else "estimated")
        print(f"\n=== Point Cloud ===")
        print(f"  Intrinsics (fx={fx:.1f} fy={fy:.1f} cx={cx:.1f} cy={cy:.1f}) [{src}]")
        print(f"  Depth range: [{min_depth_m:.2f}m, {max_depth_m:.2f}m]")

        os.makedirs(args.output, exist_ok=True)

        if args.all:
            for i, frame in enumerate(frames):
                points, colors = depth_to_colored_pointcloud(
                    frame, scale, fx, fy, cx, cy, max_depth_m, min_depth_m, args.colormap)
                pcd_path = os.path.join(args.output, f"pointcloud_{i:06d}.pcd")
                save_pcd(points, colors, pcd_path)
        else:
            idx = min(args.frame, len(frames) - 1)
            points, colors = depth_to_colored_pointcloud(
                frames[idx], scale, fx, fy, cx, cy, max_depth_m, min_depth_m, args.colormap)
            print(f"  Frame {idx}: {len(points)} valid points")
            if len(points) > 0:
                print(f"  X range: [{points[:,0].min():.3f}, {points[:,0].max():.3f}] m")
                print(f"  Y range: [{points[:,1].min():.3f}, {points[:,1].max():.3f}] m")
                print(f"  Z range: [{points[:,2].min():.3f}, {points[:,2].max():.3f}] m")
            pcd_path = os.path.join(args.output, f"pointcloud_{idx:06d}.pcd")
            save_pcd(points, colors, pcd_path)
            if args.view:
                view_pointcloud_open3d(points, colors)
    elif not args.png and not args.ascii and not args.stats:
        print("Tip: use --pointcloud to generate PCD, --png for depth image, --view for 3D viewer")

    print("\nDone!")


if __name__ == '__main__':
    main()

